# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import KV_Store_pb2 as KV__Store__pb2


class KV_Store_ServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/KV_Store.KV_Store_Service/Get',
        request_serializer=KV__Store__pb2.KV_query.SerializeToString,
        response_deserializer=KV__Store__pb2.KV_pair.FromString,
        )
    self.Set = channel.unary_unary(
        '/KV_Store.KV_Store_Service/Set',
        request_serializer=KV__Store__pb2.KV_pair.SerializeToString,
        response_deserializer=KV__Store__pb2.KV_op_result.FromString,
        )


class KV_Store_ServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KV_Store_ServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=KV__Store__pb2.KV_query.FromString,
          response_serializer=KV__Store__pb2.KV_pair.SerializeToString,
      ),
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=KV__Store__pb2.KV_pair.FromString,
          response_serializer=KV__Store__pb2.KV_op_result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'KV_Store.KV_Store_Service', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
