# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KV_Store.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='KV_Store.proto',
  package='KV_Store',
  syntax='proto3',
  serialized_pb=_b('\n\x0eKV_Store.proto\x12\x08KV_Store\"\x17\n\x08KV_query\x12\x0b\n\x03key\x18\x01 \x01(\t\"%\n\x07KV_pair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1a\n\x0cKV_op_result\x12\n\n\x02ok\x18\x01 \x01(\x08\x32r\n\x10KV_Store_Service\x12,\n\x03Get\x12\x12.KV_Store.KV_query\x1a\x11.KV_Store.KV_pair\x12\x30\n\x03Set\x12\x11.KV_Store.KV_pair\x1a\x16.KV_Store.KV_op_resultb\x06proto3')
)




_KV_QUERY = _descriptor.Descriptor(
  name='KV_query',
  full_name='KV_Store.KV_query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KV_Store.KV_query.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=51,
)


_KV_PAIR = _descriptor.Descriptor(
  name='KV_pair',
  full_name='KV_Store.KV_pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KV_Store.KV_pair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='KV_Store.KV_pair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=90,
)


_KV_OP_RESULT = _descriptor.Descriptor(
  name='KV_op_result',
  full_name='KV_Store.KV_op_result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='KV_Store.KV_op_result.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['KV_query'] = _KV_QUERY
DESCRIPTOR.message_types_by_name['KV_pair'] = _KV_PAIR
DESCRIPTOR.message_types_by_name['KV_op_result'] = _KV_OP_RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KV_query = _reflection.GeneratedProtocolMessageType('KV_query', (_message.Message,), dict(
  DESCRIPTOR = _KV_QUERY,
  __module__ = 'KV_Store_pb2'
  # @@protoc_insertion_point(class_scope:KV_Store.KV_query)
  ))
_sym_db.RegisterMessage(KV_query)

KV_pair = _reflection.GeneratedProtocolMessageType('KV_pair', (_message.Message,), dict(
  DESCRIPTOR = _KV_PAIR,
  __module__ = 'KV_Store_pb2'
  # @@protoc_insertion_point(class_scope:KV_Store.KV_pair)
  ))
_sym_db.RegisterMessage(KV_pair)

KV_op_result = _reflection.GeneratedProtocolMessageType('KV_op_result', (_message.Message,), dict(
  DESCRIPTOR = _KV_OP_RESULT,
  __module__ = 'KV_Store_pb2'
  # @@protoc_insertion_point(class_scope:KV_Store.KV_op_result)
  ))
_sym_db.RegisterMessage(KV_op_result)



_KV_STORE_SERVICE = _descriptor.ServiceDescriptor(
  name='KV_Store_Service',
  full_name='KV_Store.KV_Store_Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=120,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='KV_Store.KV_Store_Service.Get',
    index=0,
    containing_service=None,
    input_type=_KV_QUERY,
    output_type=_KV_PAIR,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Set',
    full_name='KV_Store.KV_Store_Service.Set',
    index=1,
    containing_service=None,
    input_type=_KV_PAIR,
    output_type=_KV_OP_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KV_STORE_SERVICE)

DESCRIPTOR.services_by_name['KV_Store_Service'] = _KV_STORE_SERVICE

# @@protoc_insertion_point(module_scope)
